import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "MediScribe",
  description: "Generated by create next app",
};

const inter = Inter();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className + " h-full bg-white"}>
      <body className="h-full">{children}</body>
    </html>
  );
}
